import {
  STATE_NONE,
  STATE_PLAYING,
  STATE_PAUSED,
  STATE_STOPPED,
  STATE_BUFFERING,
  STATE_READY,
} from 'react-native-track-player'
export const APP_NAME = 'digicomob'

export const MOVES = {
  LEFT: 'LEFT',
  UP: 'UP',
  RIGHT: 'RIGHT',
  DOWN: 'DOWN',
  HORIZONTAL: 'HORIZONTAL',
  VERTICAL: 'VERTICAL',
}

export const PLAYER_STATES = {
  NONE: STATE_NONE,
  PLAYING: STATE_PLAYING,
  PAUSED: STATE_PAUSED,
  STOPPED: STATE_STOPPED,
  BUFERING: STATE_BUFFERING,
  READY: STATE_READY,
}
